#!/bin/bash
#
# Run the container with default command (update database)
#

# --rm option cleans up the container file system upon exit
#   (housekeeping)
docker run --env-file ./env.list --rm dbtouch 
