#!/bin/bash
#
# Run the container to an interactive shell prompt
#

# --rm option cleans up the container file system upon exit
#   (housekeeping)
docker run --env-file ./env.list --rm -i -t dbtouch /bin/bash
